# Generated by Django 4.0.6 on 2022-07-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, default='', max_length=200, verbose_name='Email')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Компания')),
                ('is_speaker', models.BooleanField(default=False, verbose_name='Спикер')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержание')),
                ('speakers', models.ManyToManyField(related_name='meetings', to='meetup.participant', verbose_name='Спикеры')),
            ],
        ),
    ]
