# Generated by Django 4.0.6 on 2022-07-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
    ]
