# Generated by Django 4.0.6 on 2022-07-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_alter_meeting_options_alter_section_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetup.section', verbose_name='Секция'),
            preserve_default=False,
        ),
    ]
