# Generated by Django 4.0.6 on 2022-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_meeting_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='speakers',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetings', to='meetup.participant', verbose_name='Спикеры'),
        ),
    ]
