# Generated by Django 4.0.6 on 2022-07-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_alter_meeting_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetup.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_speaker': True}, related_name='meetings', to='meetup.participant', verbose_name='Спикеры'),
        ),
    ]
