# Generated by Django 4.0.6 on 2022-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0006_alter_meeting_section_alter_meeting_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='telegram_id',
            field=models.IntegerField(default=0, verbose_name='ID в Telegram'),
            preserve_default=False,
        ),
    ]
