# Generated by Django 4.0.6 on 2022-07-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_participant_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('name',)},
        ),
    ]
