# Generated by Django 4.0.6 on 2022-07-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_alter_participant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, default='', verbose_name='Ответ')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetup.participant', verbose_name='Кто задал?')),
                ('speaker', models.ForeignKey(limit_choices_to={'is_speaker': True}, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='meetup.participant', verbose_name='Кто ответил?')),
            ],
        ),
    ]
