# Generated by Django 4.0.6 on 2022-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_message_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='ID сообщения в Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
